### ISSUE TITLE
Error Saat menggunakan eval > m.quoted pada productMessage

### ISSUE THREAD

**Issue by JunaGanz** [DikaArdnt/Hisoka-Morou#144]
myfunc.js Error Saat menggunakan eval > m.quoted pada productMessage ! How to fix?
![IMG-20220711-WA0018](https://user-images.githubusercontent.com/93413322/178212978-ebeae433-0e96-4aea-baef-f9b8474c69f3.jpg)

0|index  | TypeError: Cannot set properties of undefined (setting 'mtype')
0|index  |     at exports.smsg (/storage/emulated/0/.boty/lib/myfunc.js:322:28)
0|index  |     at EventEmitter.<anonymous> (/storage/emulated/0/.boty/index.js:129:13)
0|index  |     at EventEmitter.emit (node:events:549:35)
![Screenshot_20220711_143222](https://user-images.githubusercontent.com/93413322/178212053-6042819b-d423-40bd-89c9-6d7459b71fae.jpg)

**Comment by JunaGanz** [comment]
Tapi gak penting-penting amat sih:v
