### ISSUE TITLE
Error ViewOnce

### ISSUE THREAD

**Issue by Mastrios** [DikaArdnt/Hisoka-Morou#34]
`TypeError: body.startsWith is not a function
    at hisoka (/data/data/com.termux/files/home/Hisoka-Morou/hisoka.js:42:28)
    at EventEmitter.<anonymous> (/data/data/com.termux/files/home/Hisoka-Morou/index.js:54:28)
    at EventEmitter.emit (node:events:538:35)
    at /data/data/com.termux/files/home/Hisoka-Morou/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:311:16`

Error bang ketika user mengirim view once atau gambar 1x buka.
Terima Kasih.

**Comment by Fbotzz** [comment]
Banh Fatih be like : usaha lah aowkwk

**Comment by FatihArridho** [comment]
kok bawa" nama gw

> Banh Fatih be like : usaha lah aowkwk
