### ISSUE TITLE
Taypo ye?

### ISSUE THREAD

**Issue by Bintangp02** [DikaArdnt/Hisoka-Morou#36]
> hisoka-morou@1.2.3 start
> node index.js

/home/akunbintang2008/Hisoka-Morou/index.js:143
            lastDisconnect.error?.output?.statusCode !== DisconnectReason.loggedOut ? startHisoka() : console.log('Koneksi Terputus...')
                                 ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
akunbintang2008@cloudshell:~/Hisoka-Morou$

**Comment by FatihArridho** [comment]
kok rata" pada error run di vps ya

**Comment by pa7rickr** [comment]
> 

node version?
