### ISSUE TITLE
Repo use old vbaileys 3.x.x version but installed latest 4.x.x [Termux Error]

### ISSUE THREAD

**Issue by DineshValor** [DikaArdnt/Hisoka-Morou#38]
~/Hisoka-Morou $ yarn
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
warning crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning g-i-s > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning g-i-s > request > har-validator@5.1.5: this library is no longer supported
warning g-i-s > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning google-it > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning remove.bg > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning remove.bg > unirest > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @adiwajshing/baileys@4.0.0" has unmet peer dependency "sharp@^0.29.3".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 42.52s.
~/Hisoka-Morou $ node .
node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module '/data/data/com.termux/files/home/Hisoka-Morou/node_modules/@adiwajshing/baileys/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/Hisoka-Morou/index.js:8:246)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/data/data/com.termux/files/home/Hisoka-Morou/node_modules/@adiwajshing/baileys/package.json',
  requestPath: '@adiwajshing/baileys'
}

~/Hisoka-Morou $ node .
/data/data/com.termux/files/home/Hisoka-Morou/index.js:20
const store = makeInMemoryStore({ logger: pino().child({ level: 'silent', stream: 'store' }) })
              ^

TypeError: makeInMemoryStore is not a function
    at Object.<anonymous> (/data/data/com.termux/files/home/Hisoka-Morou/index.js:20:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
~/Hisoka-Morou $

**Comment by FatihArridho** [comment]
Kalau baca readme yang bener udah dikasih tau caranya. Baca yg if error install module for termux.

**Comment by DineshValor** [comment]
> 

😐
