### ISSUE TITLE
[EROR] HELP

### ISSUE THREAD

**Issue by Bintangp02** [DikaArdnt/Hisoka-Morou#42]
[ PESAN ] Mon Feb 21 2022 06:38:34 GMT+0000 (Coordinated Universal Time) .matrix tes
=> Dari xxxxxxxxxx@s.whatsapp.net
=> Di Private Chat 62xxxxxxxxx@s.whatsapp.net
/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196
if (item.url.toString().startsWith('http://';) || item.url.toString().startsWith('https://';)) {
^
TypeError: Cannot read properties of undefined (reading 'toString')
at Object.getStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:196:18)
at Object.encryptedStream (/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:232:44)
at Object.prepareWAMessageMedia (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:70:132)
at Object.generateWAMessageContent (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:223:27)
at Object.generateWAMessage (/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:345:68)
at Object.sendMessage (/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:380:47)
at hisoka (/bin.js:1420:24)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
Koneksi Terhubung... {
connection: 'connecting',
receivedPendingNotifications: false,
qr: undefined
}
Koneksi Terhubung... { connection: 'open' }
Koneksi Terhubung... { receivedPendingNotifications: true }

**Comment by Bintangp02** [comment]
tidak hanya ini semua menu marker menu eror contoh matrix dll

**Comment by DikaArdnt** [comment]
> _tidak hanya ini, semua menu marker eror contoh matrix dll_ **contoh error di atas, makasih sekian secepatnya di fix semangat**

Api zenz sedang dalam perbaikan

**Comment by Bintangp02** [comment]
> > _tidak hanya ini, semua menu marker eror contoh matrix dll_ **contoh error di atas, makasih sekian secepatnya di fix semangat**
> 
> Api zenz sedang dalam perbaikan

Oke kalau begitu tak close aja!
