### ISSUE TITLE
[EROR] 

### ISSUE THREAD

**Issue by Bintangp02** [DikaArdnt/Hisoka-Morou#55]
/index.js:161
let reason = lastDisconnect.error ? new Boom(lastDisconnect)?.output.statusCode : 0;
^
TypeError: Cannot read properties of undefined (reading 'error')
at EventEmitter.<anonymous> (/index.js:161:30)
at EventEmitter.emit (node:events:532:35)
at /node_modules/@adiwajshing/baileys/lib/Socket/socket.js:448:12
at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by FatihArridho** [comment]
@DikaArdnt hemm peduli kah? pasti tidak:V
