### ISSUE TITLE
Lapor ndan, error

### ISSUE THREAD

**Issue by Mastrios** [DikaArdnt/Hisoka-Morou#56]
TypeError: hisoka.sendFile is not a function
    at hisoka (/storage/emulated/0/Botz-MD/hisoka.js:1889:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Ketika download instagram error ✓ 
Sc masih ori dari base. Cuma folder nya aja yang di ganti nama.

**Comment by DikaArdnt** [comment]
> TypeError: hisoka.sendFile is not a function at hisoka (/storage/emulated/0/Botz-MD/hisoka.js:1889:28) at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 
> Ketika download instagram error ✓ Sc masih ori dari base. Cuma folder nya aja yang di ganti nama.

Typo dek

**Comment by Mastrios** [comment]
> > TypeError: hisoka.sendFile is not a function at hisoka (/storage/emulated/0/Botz-MD/hisoka.js:1889:28) at processTicksAndRejections (node:internal/process/task_queues:96:5)
> > Ketika download instagram error ✓ Sc masih ori dari base. Cuma folder nya aja yang di ganti nama.
> 
> Typo dek

Sudah saya buatin function nya sendiri, ndan, saya cuma ngasih tau errornya aja 😆terimakasih

**Comment by Mikey69YT-BotDeveloper** [comment]
let reason = lastDisconnect.error ? new Boom(lastDisconnect)?.output.statusCode : 0;
                                                                     ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

I got that error
Why?
