### ISSUE TITLE
[BUG] Stuck

### ISSUE THREAD

**Issue by Bintangp02** [DikaArdnt/Hisoka-Morou#57]
[Hisoka-Morou/index.js:162
        let reason = lastDisconnect.error ? new Boom(lastDisconnect)?.output.statusCode : 0;
                                                                     ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
~/Hisoka-Morou$ ](https://replit.com/join/smbhszveow-bintangp02)

**Comment by FandyyyDev** [comment]
Slalu mati pasti pas bot nya lama ga digunain
