### ISSUE TITLE
error please fix this

### ISSUE THREAD

**Issue by sanzyx** [DikaArdnt/Hisoka-Morou#74]
adhyl@cinnamon:~/AtoZ/code/nodejs/botwangsaf/Hisoka-Morou$ node index
/home/adhyl/AtoZ/code/nodejs/botwangsaf/Hisoka-Morou/index.js:187
        let reason = new Boom(lastDisconnect?.error)?.output.statusCode
                                             ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by sanzyx** [comment]
> adhyl@cinnamon:~/AtoZ/code/nodejs/botwangsaf/Hisoka-Morou$ node index /home/adhyl/AtoZ/code/nodejs/botwangsaf/Hisoka-Morou/index.js:187 let reason = new Boom(lastDisconnect?.error)?.output.statusCode ^
> 
> SyntaxError: Unexpected token . at Module._compile (internal/modules/cjs/loader.js:723:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Function.Module.runMain (internal/modules/cjs/loader.js:831:12) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

this npm logs code
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hisoka-morou@1.2.3~prestart: hisoka-morou@1.2.3
6 info lifecycle hisoka-morou@1.2.3~start: hisoka-morou@1.2.3
7 verbose lifecycle hisoka-morou@1.2.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle hisoka-morou@1.2.3~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/adhyl/AtoZ/code/nodejs/botwangsaf/Hisoka-Morou/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle hisoka-morou@1.2.3~start: CWD: /home/adhyl/AtoZ/code/nodejs/botwangsaf/Hisoka-Morou
10 silly lifecycle hisoka-morou@1.2.3~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle hisoka-morou@1.2.3~start: Returned: code: 1  signal: null
12 info lifecycle hisoka-morou@1.2.3~start: Failed to exec start script
13 verbose stack Error: hisoka-morou@1.2.3 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid hisoka-morou@1.2.3
15 verbose cwd /home/adhyl/AtoZ/code/nodejs/botwangsaf/Hisoka-Morou
16 verbose Linux 5.4.0-104-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error hisoka-morou@1.2.3 start: `node index.js`
22 error Exit status 1
23 error Failed at the hisoka-morou@1.2.3 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ilhamsk4** [comment]
sama klo di linux error klo di windows kaga aneh

**Comment by adilhyz** [comment]
> sama klo di linux error klo di windows kaga aneh



> sama klo di linux error klo di windows kaga aneh

 😓
